## Import of data related to annual Paris production from ecological sources of energy.

### Libs imports.

In [1]:
import pandas as pd
import requests

### Connecting to ODRE's API (and testing the response's status code).

In [2]:
url = "https://odre.opendatasoft.com/api/explore/v2.1/catalog/datasets/prod-region-annuelle-enr/records"
params = {"limit" : 10}

response = requests.get(url, params=params)
response.status_code

200

### Checking the retrieved data.

In [3]:
pd.DataFrame(response.json()["results"])

,annee,nom_insee_region,code_insee_region,production_hydraulique_renouvelable,production_bioenergies_renouvelable,production_eolienne_renouvelable,production_solaire_renouvelable,production_electrique_renouvelable,production_gaz_renouvelable,production_totale_renouvelable,geo_shape_region,geo_point_region
0,2008,Île-de-France,11,59.0,629.9,NaN,0.7,689.6,0.0,689.6,"{'type': 'Feature', 'geometry': {'coordinates'...","{'lon': 2.503402421, 'lat': 48.7093154}"
1,2008,Normandie,28,149.0,338.0,301.0,0.2,788.2,0.0,788.2,"{'type': 'Feature', 'geometry': {'coordinates'...","{'lon': 0.110938291, 'lat': 49.120061533}"
2,2008,Pays de la Loire,52,19.0,63.3,255.0,3.9,341.2,0.0,341.2,"{'type': 'Feature', 'geometry': {'coordinates'...","{'lon': -0.816788181, 'lat': 47.478103923}"
3,2008,Provence-Alpes-Côte d'Azur,93,9088.2,107.3,88.0,2.2,9285.7,0.0,9285.7,"{'type': 'Feature', 'geometry': {'coordinates'...","{'lon': 6.061003171, 'lat': 43.958770089}"
4,2009,Pays de la Loire,52,16.0,103.6,400.0,18.8,538.4,0.0,538.4,"{'type': 'Feature', 'geometry': {'coordinates'...","{'lon': -0.816788181, 'lat': 47.478103923}"
5,2009,Nouvelle-Aquitaine,75,3413.0,493.8,152.0,12.7,4071.5,0.0,4071.5,"{'type': 'Feature', 'geometry': {'coordinates'...","{'lon': 0.207571781, 'lat': 45.206826366}"
6,2009,Occitanie,76,9862.9,376.1,1421.0,54.9,11714.9,0.0,11714.9,"{'type': 'Feature', 'geometry': {'coordinates'...","{'lon': 2.143923389, 'lat': 43.702500286}"
7,2009,Provence-Alpes-Côte d'Azur,93,10218.2,148.6,110.0,29.1,10505.9,0.0,10505.9,"{'type': 'Feature', 'geometry': {'coordinates'...","{'lon': 6.061003171, 'lat': 43.958770089}"
8,2010,Bourgogne-Franche-Comté,27,877.4,74.7,141.0,19.6,1112.7,0.0,1112.7,"{'type': 'Feature', 'geometry': {'coordinates'...","{'lon': 4.806856823, 'lat': 47.234282107}"
9,2010,Nouvelle-Aquitaine,75,4122.0,702.1,220.0,68.6,5112.7,0.0,5112.7,"{'type': 'Feature', 'geometry': {'coordinates'...","{'lon': 0.207571781, 'lat': 45.206826366}"

### Retrieveing the full dataset, limited to the needed region and time period

In [11]:
dataset= "prod-region-annuelle-enr"
url = f"https://odre.opendatasoft.com/api/explore/v2.1/catalog/datasets/{dataset}/records"
params = {"refine" : ["code_insee_region:11", "annee:2014", "annee:2015", "annee:2016", "annee:2017", "annee:2018", "annee:2019", "annee:2020", "annee:2021", "annee:2022", "annee:2023", "annee:2024"]}

response = requests.get(url, params=params)
df = pd.DataFrame(response.json()["results"])

df.head()

,annee,nom_insee_region,code_insee_region,production_hydraulique_renouvelable,production_bioenergies_renouvelable,production_eolienne_renouvelable,production_solaire_renouvelable,production_electrique_renouvelable,production_gaz_renouvelable,production_totale_renouvelable,geo_shape_region,geo_point_region
0,2020,Île-de-France,11,42.838,747.31,265.68,126.44,1182.268,290.2,1472.468,"{'type': 'Feature', 'geometry': {'coordinates'...","{'lon': 2.503402421, 'lat': 48.7093154}"
1,2014,Île-de-France,11,52.227,742.42,37.90,66.12,898.667,NaN,898.667,"{'type': 'Feature', 'geometry': {'coordinates'...","{'lon': 2.503402421, 'lat': 48.7093154}"
2,2022,Île-de-France,11,57.417,772.43,322.15,209.21,1361.207,718.9,2080.107,"{'type': 'Feature', 'geometry': {'coordinates'...","{'lon': 2.503402421, 'lat': 48.7093154}"
3,2015,Île-de-France,11,55.222,707.20,52.71,72.02,887.152,37.1,924.252,"{'type': 'Feature', 'geometry': {'coordinates'...","{'lon': 2.503402421, 'lat': 48.7093154}"
4,2017,Île-de-France,11,58.685,849.87,91.73,70.08,1070.365,77.5,1147.865,"{'type': 'Feature', 'geometry': {'coordinates'...","{'lon': 2.503402421, 'lat': 48.7093154}"

### Saving to CSV

In [13]:
df.to_csv(f"{dataset}_ODRE.csv", sep=";", index=False)