## Tree planting in Paris between 2020 and 2025, with area size and location, and number of trees planted.

### Importing libraries

In [2]:
import pandas as pd
import requests

### Connecting to Paris Data's API (and testing the response's status code)

In [3]:
params = {"select":"nom_projet, arrond, date_fin_t, ope_statut, ope_type, ind_arb_plant, st_area_shape, geo_shape"}
response = requests.get('https://opendata.paris.fr/api/explore/v2.1/catalog/datasets/arbres-plantes-par-projet/records?',params=params)
response.status_code

200

In [4]:
pd.DataFrame(response.json()["results"])

,nom_projet,arrond,date_fin_t,ope_statut,ope_type,ind_arb_plant,st_area_shape,geo_shape
0,ARB - TALUS BP 24-11,19,2025-03-19T01:00:00+00:00,Réalisé,Arbre,107.0,551.565519,"{'type': 'Feature', 'geometry': {'coordinates'..."
1,ARB - TALUS BP 15-04,16,2023-03-30T02:00:00+00:00,Réalisé,Arbre,300.0,1283.952296,"{'type': 'Feature', 'geometry': {'coordinates'..."
2,ARB - TALUS BP 24-07 Pte d'Aubervilliers,19,2023-03-31T02:00:00+00:00,Réalisé,Arbre,35.0,1477.270473,"{'type': 'Feature', 'geometry': {'coordinates'..."
3,Replantations Jardins 2022-2023 - 15e ardt,15,2023-03-30T02:00:00+00:00,Réalisé,Arbre,238.0,72.078442,"{'type': 'Feature', 'geometry': {'coordinates'..."
4,Replantations Cimetières 2022-2023 - 17e ardt,17,2023-03-31T02:00:00+00:00,Réalisé,Arbre,1.0,85.317605,"{'type': 'Feature', 'geometry': {'coordinates'..."
5,Replantations DJS 2022-2023 - 18e ardt,18,2023-03-31T02:00:00+00:00,Réalisé,Arbre,1.0,73.614019,"{'type': 'Feature', 'geometry': {'coordinates'..."
6,Replantations Jardins 2022-2023 - 19e ardt,19,2023-03-30T02:00:00+00:00,Réalisé,Arbre,16.0,74.926716,"{'type': 'Feature', 'geometry': {'coordinates'..."
7,Nouvelles plantations dans les cimetières 2022...,20,2023-03-31T02:00:00+00:00,Réalisé,Arbre,6.0,1811.998456,"{'type': 'Feature', 'geometry': {'coordinates'..."
8,Nouveaux arbres DJS 2022-2023 - 17e ardt,17,2023-03-31T02:00:00+00:00,Réalisé,Arbre,15.0,112.007380,"{'type': 'Feature', 'geometry': {'coordinates'..."
9,COURS OASIS EE Jussienne 3,2,2023-09-01T02:00:00+00:00,Réalisé,Végétalisation de l’espace public,1.0,347.222039,"{'type': 'Feature', 'geometry': {'coordinates'..."

### Retrieving the dataset as a .csv and converting it to a DataFrame

In [5]:
dataset_id = 'arbres-plantes-par-projet'
export_url = f'https://opendata.paris.fr/api/explore/v2.1/catalog/datasets/{dataset_id}/exports/csv'
params = {"select": "nom_projet, arrond, date_fin_t, ope_statut, ope_type, ind_arb_plant, st_area_shape, geo_shape"}

# Downloading the csv of the full dataset
response = requests.get(export_url, params=params)
with open(f"{dataset_id}_Paris_Data.csv", "wb") as f:
    f.write(response.content)

# Converting the csv into a DataFrame
df = pd.read_csv(f"{dataset_id}_Paris_Data.csv", sep=";")

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 806 entries, 0 to 805
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   nom_projet     806 non-null    object
 1   arrond         806 non-null    int64
 2   date_fin_t     806 non-null    object
 3   ope_statut     806 non-null    object
 4   ope_type       765 non-null    object
 5   ind_arb_plant  806 non-null    float64
 6   st_area_shape  806 non-null    float64
 7   geo_shape      806 non-null    object
dtypes: float64(2), int64(1), object(5)
memory usage: 50.5+ KB

In [7]:
df.head()

,nom_projet,arrond,date_fin_t,ope_statut,ope_type,ind_arb_plant,st_area_shape,geo_shape
0,ARB - TALUS BP 15-06 - Phase 2,16,2022-03-31T02:00:00+00:00,Réalisé,Arbre,65.0,435.385676,"{""coordinates"": [[[2.2721890699147806, 48.8709..."
1,ARB - TALUS BP 10-05,16,2025-03-19T01:00:00+00:00,Réalisé,Arbre,15.0,160.681363,"{""coordinates"": [[[2.2553584771203816, 48.8377..."
2,Parc André Citroën (rénovation des serres et d...,15,2024-06-30T02:00:00+00:00,Réalisé,Nouvelle surface d’espaces verts,2716.0,974.305225,"{""coordinates"": [[[2.27396714628552, 48.840886..."
3,ARB - TALUS BP 15-12 - Phase 2,16,2021-02-08T01:00:00+00:00,Réalisé,Arbre,90.0,341.776542,"{""coordinates"": [[[2.2760749394551554, 48.8750..."
4,ARB - TALUS BP 15-01 Pl de Colombie,16,2023-03-30T02:00:00+00:00,Réalisé,Arbre,29.0,456.249731,"{""coordinates"": [[[2.2671647439619242, 48.8643..."